### ISSUE TITLE
Investigate Initialize of pdf Files

### ISSUE THREAD

**Issue by philcarrillo** [weenhanceit/autism-funding#13]
Investigate the feasibility of initialing pdf files with data

**Comment by lcreid** [comment]
I've created a pdf branch and installed what's needed to fill out the PDF forms. I created a PDF for a Request to Pay (RTP) with my name in the first and last name fields in the rails console. The commit for that is pushed to the pdf branch on Github. Read the extended commit message (click on the three dots by the commit) to see important instructions.

I'm now trying to figure out where we would put the printing into the app. I want to have a model for an instance of an RTP, and in fact instances for each PDF generation, so that the user can keep track of when a form was printed. So that means I will have a controller called "rtp", with all the usual actions, plus one to render the PDF.

**Comment by lcreid** [comment]
I pushed the "pdf" branch with one test case that simply fills out the RTP (cf_0925) with dummy data and leaves it in `/tmp`.
